version: '3.8'

services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - mongo
      - reservations
      - auth
      - payments
      - notifications
      - gateway

  reservations:
    build:
      context: ../
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - ../:/usr/src/app

  auth:
    build:
      context: ../
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - ../:/usr/src/app

  payments:
    build:
      context: ../
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'
    volumes:
      - ../:/usr/src/app

  notifications:
    build:
      context: ../
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3005:3005'
    volumes:
      - ../:/usr/src/app
  gateway:
    build:
      context: ../
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ../apps/gateway/.env
    volumes:
      - ..:/usr/src/app
    ports:
      - '3004:3004'
  mongo:
    image: mongo
